# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 3.6.0
  - release
  - devel
warnings_are_errors: true
sudo: required
cache: packages

r_github_packages:
  - jimhester/covr

dist: xenial
addons:
  apt:
    packages: libnode-dev

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n r-gluonts python=3.6
  - conda activate r-gluonts
  - conda install pip
  - pip install mxnet==1.6 gluonts==0.5.2 numpy==1.16.6 pandas==1.0.5 scikit-learn==0.23.2 matplotlib==3.3.2 seaborn==0.11.0 pathlib==1.0.1

