name: r-gluonts
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - mxnet~=1.7
    - gluonts==0.8.0
    - numpy==1.17.2
    - pandas==1.0.5
    - pathlib==1.0.1
    - ujson
